### PR TITLE
Adding capture matcher.

### PR DESCRIPTION
**Pull request by yortyrh**

### CODE REVIEW

**Comment by NiGhTTraX** [comment]
Hey @yortyrh, is this similar to Mockito's [`ArgumentCaptor`](https://javadoc.io/static/org.mockito/mockito-core/3.12.4/org/mockito/Mockito.html#captors)? Could you please clarify what the use case for this is?

**Comment by yortyrh** [comment]
Yes, same idea of Mockito's ArgumentCaptor.
Same scenarios where we need ArgumentCaptor in mockito, or jest call arguments array.

Do you need particular examples?
Do you think this is not needed?

**Comment by yortyrh** [comment]
I needed it to test that two calls to different methods were done with functions with the same return for particular parameters.
Then I had to capture call 1, then capture call 2 then expect the result of capture1 was equal to the result of capture2. This happened when I was migrating a test from jest and had to implement this capture utility class...

````
/**
* mapper example: {uid: '1', name: 'name'} -- mapper --> {id: '1', userName: 'name'}
* const x = await get( 'user/1', (x) => ({id: x.uid, userName: x.name}) )
*/
async function get(url, mapper);

async function profile(userId);
````

Let's test the profile function:
We would need: 
````
when(profile('1', arg2.capture())).thenResolve({id: '1', userName: 'name'});
// Whatever calls profile function.
expect(arg2.get()({uid: '1', name: 'name'})).toMatch({id: '1', userName: 'name'});
````
Any idea to resolve this without capture?

**Comment by NiGhTTraX** [comment]
Thanks for clarifying, @yortyrh! I see how that can be useful, though I would try to redesign the code to make the callback an implementation detail of either the code under test, or its dependency.

I cherry picked your commit and renamed the matcher to `It.willCapture` in 987e3910db4abbce4ca4b65e3c54c32191e30ddd. This is now released in `7.2.0`. Thanks for your contribution!

**Pull request closed without merging**
